apiVersion: v1
kind: Service
metadata:
  name: notifications-api-service-minikube
  labels:
    app: notifications-api
spec:
  selector:
    app: notifications-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
      name: http
  type: NodePort   # Para Minikube

