apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
  labels:
    app: notifications-api
spec:
  replicas: 2   # número de instancias (para alta disponibilidad)
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      containers:
        - name: notifications-api
          image: notifications-api:latest   # la imagen Docker que creaste
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/notifications_db
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_PROFILES_ACTIVE
              value: mysql
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

